"""
Validate Processed Data — RADIal
==================================
Checks that all `.npz` files generated by preprocessing are:
  1. Readable (not corrupted)
  2. Correct shape
  3. Non-empty (occupancy > 0)
  4. Free of NaN / Inf
  5. Within expected ranges (intensity ∈ [0,1], velocity ∈ [-1,1], occ ∈ {0,1})
  6. Split coverage (train/test) is consistent

Usage:
    python scripts/validate_processed_data.py --config configs/radial.yaml

    # Only the first 100 files (quick check)
    python scripts/validate_processed_data.py --config configs/radial.yaml --n_samples 100

    # Verbose: print stats for each OK file
    python scripts/validate_processed_data.py --config configs/radial.yaml --verbose

Output:
    - Console summary
    - bad_samples.json → list of problematic files (path + reasons)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
from omegaconf import OmegaConf
from tqdm import tqdm


# Expected shapes for RADIal (paper Section 4.1)
EXPECTED_SHAPES = {
    "tensor_rae2": (480, 736, 11, 2),
    "rad_map":     (480, 736, 16),
    "lidar_occ":   (480, 736, 11),
}

# Expected value ranges
VALUE_RANGES = {
    "tensor_rae2_intensity": (0.0, 1.0),   # channel 0: log-normalized
    "tensor_rae2_velocity":  (-1.0, 1.0),  # channel 1: clipped velocity
    "rad_map":               (0.0, 1.0),   # log-normalized
    "lidar_occ":             (0.0, 1.0),   # binary {0, 1}
}


def check_npz(npz_path: Path, verbose: bool = False) -> list[str]:
    """
    Check a single `.npz` file.

    Returns:
        List of issues (empty list = OK).
    """
    issues = []

    # ── 1. Readability ──────────────────────────────────────────────
    try:
        data = np.load(str(npz_path))
    except Exception as e:
        return [f"CORRUPTED — cannot read: {e}"]

    # ── 2. Required keys ────────────────────────────────────────────
    for key in EXPECTED_SHAPES:
        if key not in data:
            issues.append(f"Missing key: '{key}'")

    if issues:
        return issues   # cannot proceed without keys

    tensor_rae2 = data["tensor_rae2"]
    rad_map     = data["rad_map"]
    lidar_occ   = data["lidar_occ"]

    # ── 3. Shapes ───────────────────────────────────────────────────
    for key, arr in [("tensor_rae2", tensor_rae2),
                     ("rad_map", rad_map),
                     ("lidar_occ", lidar_occ)]:
        if arr.shape != EXPECTED_SHAPES[key]:
            issues.append(f"Wrong shape for {key}: {arr.shape} (expected {EXPECTED_SHAPES[key]})")

    if issues:
        return issues

    # ── 4. float32 dtype ────────────────────────────────────────────
    for key, arr in [("tensor_rae2", tensor_rae2),
                     ("rad_map", rad_map),
                     ("lidar_occ", lidar_occ)]:
        if arr.dtype != np.float32:
            issues.append(f"Wrong dtype for {key}: {arr.dtype} (expected float32)")

    # ── 5. NaN / Inf ────────────────────────────────────────────────
    for key, arr in [("tensor_rae2", tensor_rae2),
                     ("rad_map", rad_map),
                     ("lidar_occ", lidar_occ)]:
        if np.isnan(arr).any():
            issues.append(f"Contains NaN: {key}")
        if np.isinf(arr).any():
            issues.append(f"Contains Inf: {key}")

    if issues:
        return issues

    # ── 6. Value ranges ─────────────────────────────────────────────
    intensity = tensor_rae2[..., 0]
    velocity  = tensor_rae2[..., 1]

    if intensity.min() < -0.01 or intensity.max() > 1.01:
        issues.append(f"Intensità fuori range [0,1]: min={intensity.min():.4f} max={intensity.max():.4f}")

    if velocity.min() < -1.01 or velocity.max() > 1.01:
        issues.append(f"Velocità fuori range [-1,1]: min={velocity.min():.4f} max={velocity.max():.4f}")

    if rad_map.min() < -0.01 or rad_map.max() > 1.01:
        issues.append(f"rad_map fuori range [0,1]: min={rad_map.min():.4f} max={rad_map.max():.4f}")

    occ_vals = np.unique(lidar_occ)
    if not np.all(np.isin(occ_vals, [0.0, 1.0])):
        issues.append(f"lidar_occ is not binary: unique values = {occ_vals[:10]}")

    # ── 7. Non-empty occupancy ──────────────────────────────────────
    occ_sum = lidar_occ.sum()
    if occ_sum == 0:
        issues.append("lidar_occ is all zeros (no LiDAR points voxelized)")

    # ── 8. Radar intensity not flat ─────────────────────────────────
    if intensity.max() == 0:
        issues.append("tensor_rae2 intensity is all zeros (beamforming failed?)")

    if verbose and not issues:
        occ_pct = 100 * occ_sum / lidar_occ.size
        print(f"  {npz_path.stem}: OK  "
              f"occ={occ_pct:.2f}%  "
              f"I_max={intensity.max():.3f}  "
              f"V_range=[{velocity.min():.2f},{velocity.max():.2f}]")

    return issues


def main():
    parser = argparse.ArgumentParser(description="Validate RADIal processed .npz files")
    parser.add_argument("--config",    required=True,        help="configs/radial.yaml")
    parser.add_argument("--n_samples", type=int, default=None, help="Check only N files (None=all)")
    parser.add_argument("--verbose",   action="store_true",  help="Print stats for each OK file")
    args = parser.parse_args()

    cfg       = OmegaConf.load(args.config)
    proc_path = Path(cfg.dataset.processed_path)
    index_path = proc_path / "index.json"

    # List files to check
    if index_path.exists():
        with open(index_path) as f:
            index = json.load(f)
        npz_paths = [Path(e["npz_path"]) for e in index]
        splits    = {e["sample_id"]: e["split"] for e in index}
    else:
        print("⚠️  index.json not found — scanning all .npz in the folder")
        npz_paths = sorted(proc_path.glob("*.npz"))
        splits    = {}

    if args.n_samples:
        npz_paths = npz_paths[:args.n_samples]

    total = len(npz_paths)
    print(f"\n{'='*60}")
    print(f"RADIal processed data validation")
    print(f"{'='*60}")
    print(f"  Folder: {proc_path}")
    print(f"  Files to check: {total}")
    print(f"{'='*60}\n")

    # Run checks
    ok_count    = 0
    bad_count   = 0
    bad_samples = []

    stats_occ   = []   # occupancy % for OK files
    stats_i_max = []   # max intensity for OK files

    for npz_path in tqdm(npz_paths, desc="Validating"):
        issues = check_npz(npz_path, verbose=args.verbose)

        if not issues:
            ok_count += 1
            try:
                d = np.load(str(npz_path))
                stats_occ.append(100 * d["lidar_occ"].sum() / d["lidar_occ"].size)
                stats_i_max.append(float(d["tensor_rae2"][..., 0].max()))
            except Exception:
                pass
        else:
            bad_count += 1
            bad_samples.append({
                "path":   str(npz_path),
                "issues": issues,
            })
            if args.verbose:
                print(f"  ✗ {npz_path.stem}: {issues}")

    # Save list of problematic files
    bad_path = proc_path / "bad_samples.json"
    with open(bad_path, "w") as f:
        json.dump(bad_samples, f, indent=2)

    # Split stats
    train_count = sum(1 for e in index if e["split"] == "train") if index_path.exists() else "N/A"
    test_count  = sum(1 for e in index if e["split"] == "test")  if index_path.exists() else "N/A"

    # Print summary
    print(f"\n{'='*60}")
    print(f"VALIDATION SUMMARY")
    print(f"{'='*60}")
    print(f"  Files checked: {total}")
    print(f"  ✓ OK:             {ok_count}  ({100*ok_count/max(total,1):.1f}%)")
    print(f"  ✗ Problemi:       {bad_count}  ({100*bad_count/max(total,1):.1f}%)")

    if splits:
        print(f"\n  Splits in index:")
        print(f"    Train: {train_count}")
        print(f"    Test:  {test_count}")

    if stats_occ:
        print(f"\n  LiDAR occupancy stats (OK files):")
        print(f"    Mean:   {np.mean(stats_occ):.3f}%")
        print(f"    Min:    {np.min(stats_occ):.3f}%")
        print(f"    Max:    {np.max(stats_occ):.3f}%")
        zero_occ = sum(1 for v in stats_occ if v < 0.001)
        if zero_occ:
            print(f"    ⚠️  Files with occupancy ~0: {zero_occ}")

    if stats_i_max:
        print(f"\n  Radar intensity stats (OK files):")
        print(f"    Mean max_intensity: {np.mean(stats_i_max):.4f}")
        zero_i = sum(1 for v in stats_i_max if v < 0.001)
        if zero_i:
            print(f"    ⚠️  Files with intensity ~0: {zero_i}")

    if bad_count > 0:
        print(f"\n  First issues found:")
        for b in bad_samples[:5]:
            print(f"    {Path(b['path']).stem}: {b['issues']}")
        print(f"\n  Full list saved to: {bad_path}")
    else:
        print(f"\n  All files look valid!")

    print(f"{'='*60}")

    # Non-zero exit code when issues are present (useful for CI/scripts)
    sys.exit(1 if bad_count > 0 else 0)


if __name__ == "__main__":
    main()
